
export const $namespaces = Symbol('namespaces'),
	$decompose = Symbol('decompose()'),
	$funcs = Symbol('functions'),
	$args = Symbol('arguments'),
	$arg = Symbol('arg'),
	$param = Symbol('parameter'),
	$val = Symbol('val'),
	$root = Symbol('root'),
	$maybe = Symbol('maybe'),
	$value = Symbol('value'),
	$thisArg = Symbol('this'),
	$decomposition = Symbol('decomposition'),
	_$ = Symbol('call'),
	$methods = Symbol('methods');
